# Generated by Django 4.1.4 on 2022-12-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
