# Generated by Django 4.1.4 on 2022-12-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.FloatField(default=0.0),
        ),
    ]
