# Generated by Django 4.1 on 2022-08-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Imagem',
            new_name='imagem',
        ),
    ]
