# Generated by Django 4.1.4 on 2022-12-28 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_meu_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
