# Generated by Django 4.1 on 2022-08-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_imagem_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='principal.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='camisa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Preço do Produto'),
            preserve_default=False,
        ),
    ]
