# Generated by Django 4.1.4 on 2022-12-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_pedido_quantidade_alter_pedido_valor_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_cliente',
            field=models.IntegerField(),
        ),
    ]
