# Generated by Django 4.1.4 on 2022-12-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='nota_fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('id_adress', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
