# Generated by Django 4.1.4 on 2022-12-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_pedido_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_cliente',
            field=models.IntegerField(),
        ),
    ]
