# Generated by Django 4.1.4 on 2022-12-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='id_adress',
            field=models.CharField(max_length=255),
        ),
    ]
