# Generated by Django 4.1.3 on 2022-11-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nome_categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='categoria_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='descricao_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='imagem_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='valor_produto',
        ),
    ]
