# Generated by Django 4.1.3 on 2022-11-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_rename_nome_categoria_nome_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='email_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='nome_cliente',
        ),
    ]
