# Generated by Django 4.1.4 on 2022-12-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_remove_nota_fiscal_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meu_usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
