# Generated by Django 4.1.3 on 2022-12-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_rename_email_cliente_email_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha_cliente',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
