# Generated by Django 4.1.4 on 2022-12-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_endereco_cliente_senha_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='senha_cliente',
            field=models.CharField(max_length=8),
        ),
    ]
