# Generated by Django 4.1.4 on 2022-12-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_alter_meu_usuario_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nota_fiscal',
        ),
    ]
