# Generated by Django 4.1.4 on 2022-12-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_alter_cliente_senha_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_endereco',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='principal.endereco'),
        ),
    ]
