# Generated by Django 4.1.4 on 2022-12-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_cliente_id_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_endereco',
            field=models.ManyToManyField(default=True, to='principal.endereco'),
        ),
    ]
