# Generated by Django 4.1.4 on 2022-12-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_cliente_bairro_cliente_cidade_cliente_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_endereco',
        ),
        migrations.DeleteModel(
            name='endereco',
        ),
    ]
