# Generated by Django 4.1.4 on 2022-12-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_remove_cliente_bairro_remove_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(max_length=254, verbose_name='Email: '),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=100, verbose_name='Nome completo: '),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='senha_cliente',
            field=models.CharField(max_length=8, verbose_name='Senha: '),
        ),
    ]
