# Generated by Django 4.1.4 on 2022-12-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_alter_cliente_email_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qnt_disponivel',
            field=models.IntegerField(default=True),
        ),
    ]
